pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Iam-Bala1406/aws-devops-for_beginers.git'  // Your repo URL
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Print Hello World') {
            steps {
                echo 'Hello, World! Jenkins Pipeline with Maven!'
            }
        }
    }
}

        }
    }
}
